### ISSUE TITLE
A home for these functions

### ISSUE THREAD

**Issue by andrewthad** [lens/lens-aeson#15]
I've got these two helper functions for making JSON instances. These have ended up in a `Misc` module in several of my projects:

```
--------------
-- Helpers for stealing JSON instances from an isomorphic type
-------------
isoParseJSON :: FromJSON a => Iso' b a -> Value -> Parser b
isoParseJSON i v = view (mapping (from i)) (parseJSON v)

isoToJSON :: ToJSON a => Iso' b a -> b -> Value
isoToJSON i b = toJSON (view i b)
```

The idea is that they are used for getting free instances from an isomorphic type:

```
-- Assume that Cat has instances for FromJSON and ToJSON
myIso :: Iso' Dog Cat
myIso = ...
instance FromJSON Dog where
  parseJSON = isoParseJSON myIso
instance ToJSON Dog where
  toJSON = isoToJSON myIso
```

For simple newtype wrapping, you can just use GND instead, but in more complicated situations, that may not be an option. Anyway, since this package is sort of where lens and aeson meet, I thought that it may be an appropriate home for these, even though the scope is a little different than what these functions do. Let me know what you think. Thanks.

**Comment by ekmett** [comment]
Going through the issue backlog (long though it may be!)

These don't fit the general `lens` style usage pattern in several ways. 

* Neither one of these actually uses the full `Iso`, just one direction. 
* The former needs a Review, the latter needs a Getter, and basically just uses them as functions. 
* Then they take the polymorphic types rather than the monomorphic subtypes they actually need. 
* In generally we never pass getters.

If you break them down to calls to just the function rather than the full iso, they are basically just straight function compositions.

**Comment by andrewthad** [comment]
For the reasons you cite, these functions no longer seem like a good idea to me. Closing.
