### ISSUE TITLE
`"{}" & _Object . at "a" . _JSON .~ Just (3 :: Int)` hangs

### ISSUE THREAD

**Issue by shak-mar** [lens/lens-aeson#16]
When I type
``` haskell
"{}" & _Object . at "a" . _JSON .~ Just (3 :: Int)
```
into ghci, it outputs one `"` and then hangs. I would expect it to output `"{\"a\":3}"`. Why does this happen? Is there a different way to add a new key to the Object that I should use?

**Comment by shak-mar** [comment]
I forgot to mention I created this instance:
``` haskell
instance AsJSON t => AsJSON (Maybe t) where
    _JSON = _JSON
```

**Comment by glguy** [comment]
It hangs because this instance is implemented in terms of itself

**Comment by Taneb** [comment]
Firstly, what glguy said, it hangs because `_JSON` for `Maybe t` is just defined to be `_JSON`. This is similar to defining `foo :: () -> Void; foo = foo`, which compiles but obviously doesn't do anything useful. However, an `AsJSON` instance for `Maybe t` isn't what you want, as here it will be given `Nothing` and can only apply a function to a `Just` value.

How about something like `"{}" & _Object . at "a" ?~ _JSON # 3`? This has the output you expected.

**Comment by shak-mar** [comment]
Oh, that seems to make sense, now I’m feeling silly… Thanks.
