### ISSUE TITLE
Generalize _JSON to allow it to change the type of a

### ISSUE THREAD

**Issue by janpath** [lens/lens-aeson#29]
Currently `_JSON` has the type `(FromJSON a, ToJSON a) => Prism' t a`, but I do not think that there is any reason for it not to be `(FromJSON a, ToJSON b) => Prim t t a b`. `t` does not care what the JSON it holds represents. I made pull request #28 some time ago, but it was ignored. Is this not worth the minor breaking change, or do you plan to merge it at a later time? Or did you just not have time to review it?

One reason I could think of against this change would be, that if we instantiate `_JSON :: Prism t t a b`, where we do not have `ToJSON a` and `FromJSON b`, the prism laws are not well defined. For example the law `preview l (review l b) ≡ Just b` requires, that we can instantiate the prism with `Prism' t a`, which isn't possible in the above setting. But is that really such a big problem? And if it is, we can still give `_JSON` the type `(FromJSON a, ToJSON a, FromJSON b, ToJSON b) => Prism t t a b`.

**edit:** I think the last point is moot anyway, as `a` and `b` are not part of the parameters to `AsJSON` and therefore `_JSON :: Prism' t a` just has to be lawful if it is defined, that is if `a` is both `FromJSON` and `ToJSON`. At least that's how I would interpret the prism laws.

**Comment by ekmett** [comment]
The real problem with this is that with those being separate types there are a lot of combinators you will go to reach for in lens, that will fail to typecheck because they'll leave `a` or `b` ambiguous and no defaulting can happen.

This isn't a problem with allowing it, so much as making it behave well if we do allow it. It was monomorphized deliberately based on user experience with the other design, so rolling that back isn't something to do lightly.

Another option is to allow a more general type at an explicit `_JSON'` or to restrict `_JSON'` and liberalize `_JSON`. 

It is a lot easier to justify a `_JSON'` as an API extension than breaking all current users, despite the fact that this would get the convention backwards.

**Comment by ekmett** [comment]
Generalized in head. Decided to generalize `_JSON` and add `_JSON'` for the existing behavior favoring long term consistency over any short term pain.
